spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    url: jdbc:mysql://144.22.188.2:3306/mirante_upcare
    username: root
    password: 123456
    hikari:
      data-source-properties:
        https.proxyHost: proxy.ceuma.edu.br
        https.proxyPort: 3128

  jpa:
    properties:
       hibernate:
         ddl-auto: update
         dialect: org.hibernate.dialect.MySQLDialect
         show_sql: true

info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
  build:
    artifact: '@project.artifactId@'
    group: '@project.groupId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
server:
  port: 8080
  servlet:
    context-path: /upcare
  error:
    include-message: always