---
spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    url: jdbc:h2:mem:upcare
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
