spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    url: jdbc:mysql://localhost:3306/upcare
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
  build:
    artifact: '@project.artifactId@'
    group: '@project.groupId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
server:
  port: 8080
  servlet:
    context-path: /upcare
  error:
    include-message: always